### ISSUE TITLE
Ping and MTR look OK while WGET says destination unreachable

### ISSUE THREAD

**Issue by Joe-Ng-1998** [lixingcong/minivtun-openwrt#1]
Please help!

# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=47 time=207 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=47 time=207 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=47 time=206 ms
------
Keys:  Help   Display mode   Restart statistics   Order of fields
quit                       Packets               Pings
 Host                    Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. 10.1.1.1              0.0%    14  202.4 202.3 201.9 203.5   0.3
 2. 192.168.71.206        0.0%    14  208.4 208.6 205.2 214.5   1.8
    203.79.255.129
 3. 203.79.255.129        0.0%    14  208.2 209.7 207.9 226.9   4.9
 4. 211.76.96.162         0.0%    14  208.3 208.9 208.0 212.1   0.9
 5. 72.14.214.205         0.0%    14  209.1 209.1 208.3 212.7   1.0
 6. 108.170.244.34        0.0%    14  209.1 209.6 208.6 216.5   2.0
 7. 108.170.238.104       0.0%    13  209.4 209.8 209.1 212.8   0.8
 8. 72.14.232.139         0.0%    13  212.2 212.2 211.1 212.9   0.0
 9. 209.85.247.57         0.0%    13  211.9 211.7 211.4 212.1   0.0
------
# wget https://google.com/
--2017-01-28 23:50:06--  https://google.com/
Resolving google.com (google.com)... 216.58.200.238, 2404:6800:4008:802::200e
Connecting to google.com (google.com)|216.58.200.238|:443... failed: Connection timed out.
Connecting to google.com (google.com)|2404:6800:4008:802::200e|:443... failed: Network is unreachable.
------
 wget http://163.com/
--2017-01-28 23:50:41--  http://163.com/
Resolving 163.com (163.com)... 123.58.180.7, 123.58.180.8
Connecting to 163.com (163.com)|123.58.180.7|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.163.com/ [following]
--2017-01-28 23:50:41--  http://www.163.com/
Resolving www.163.com (www.163.com)... 211.76.108.13, 211.76.108.12, 211.76.108.14
Connecting to www.163.com (www.163.com)|211.76.108.13|:80... failed: Connection timed out.
Connecting to www.163.com (www.163.com)|211.76.108.12|:80... failed: Connection timed out.
Connecting to www.163.com (www.163.com)|211.76.108.14|:80... failed: Connection timed out.
Retrying.
--2017-01-28 23:50:51--  (try: 2)  http://www.163.com/
Connecting to www.163.com (www.163.com)|211.76.108.13|:80... ^C

**Comment by lixingcong** [comment]
What is your command?

For example, mine is:

	# sever
	/usr/sbin/minivtun -l 0.0.0.0:555 -a 172.16.0.1/24 -e password
	
	# client
	/usr/sbin/minivtun -r 88.88.88.88:555 -a 172.16.0.3/24 -e password

if you execute this command in client side, you should see the ping echo.

	ping 172.16.0.1

Please check your command.

**Comment by Joe-Ng-1998** [comment]
I used your linux-server and linux-client scripts. And 172.16.0.1 is the server with NAT set up. So I can ping 172.16.0.1 and 8.8.8.8 from 172.16.0.3. Running mtr 8.8.8.8 on 172.16.0.3 also seemed OK.

But running wget https://google.com/ gives me the error above. Basically I cloud not get any TCP/UDP traffic through the NAT on the server. Oddly though, I can correctly get ICMP through as demonstrated in the mtr and ping test.

Do you want to take a look at my run.sh settings o both the server end and client end?

**Comment by lixingcong** [comment]
Sorry I am not the author of minivtun and have no idea on it. I even don't know how minivtun works. I just make a openwrt version here.

I can not reproduce your problem according to your description.

Please open a new issue [here](https://github.com/rssnsj/minivtun)
