### ISSUE TITLE
是不是不支持作为服务端？

### ISSUE THREAD

**Issue by mmmiii33** [lixingcong/minivtun-openwrt#2]
安装完毕后测试作为客户端完全没问题，但是作为服务端的时候数据就不通了，客户端一直重复Reconnected。
客户端：
Reconnected to x.x.x.x:6000.
Connection went bad. About to reconnect.

服务端：
Mini virtual tunnelling server on 0.0.0.0:6000, interface: mv1.
Online clients: 0, addresses: 0
Online clients: 0, addresses: 0
Online clients: 0, addresses: 0
Online clients: 0, addresses: 0
Online clients: 0, addresses: 0

**Comment by lixingcong** [comment]
不清楚哦，如果路由器是能获得公网ip应该可以吧

或检查一下openwrt的防火墙规则，是不是入站规则INPUT被reject了。。。

我不是minivtun作者，你可以去项目发起issue

https://github.com/rssnsj/minivtun/issues

**Comment by mmmiii33** [comment]
感谢，确实是被reject掉了。
